In [165]:
import torch
torch.manual_seed(1)

In [166]:
#Vector
v_data=[1.,2.,3.]
V=torch.tensor(v_data)
print(V)

#Matrix
M_data=[[1.,2.,3.],[4.,5.,6.]]
M=torch.tensor(M_data)
print(M)

#3-D Data
T_data=[[[1.,2.],[3.,4.]],
        [[5.,6.],[7.,8.]]]
T=torch.tensor(T_data)
print(T)
print(T.shape)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([2, 2, 2])


In [167]:

print(V[0])
print(V[0].item())
print(M[0])
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [168]:
torch.randn((3,4,5))

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])

In [169]:
x=torch.tensor([1.,2.,3.])
y=torch.tensor([4.,5.,6.])
z=x+y
print(z)

tensor([5., 7., 9.])


In [170]:
x_1=torch.rand(2,5)
y_1=torch.rand(3,5)
z_1=torch.cat([x_1,y_1])
print(z_1)

x_2=torch.randn(2,3)
y_2=torch.randn(2,5)
z_2=torch.cat([x_2,y_2],1)
print(z_2)


tensor([[0.6818, 0.7479, 0.0369, 0.7517, 0.1484],
        [0.1227, 0.5304, 0.4148, 0.7937, 0.2104],
        [0.0555, 0.8639, 0.4259, 0.7812, 0.6607],
        [0.1251, 0.6004, 0.6201, 0.1652, 0.2628],
        [0.6705, 0.5896, 0.2873, 0.3486, 0.9579]])
tensor([[-0.1010,  1.6197, -0.5581, -1.6396,  2.3906, -0.5024,  0.0476, -1.1322],
        [-0.3964,  1.4130, -2.6119, -0.0179,  0.1280, -0.5552, -0.4575, -1.9599]])


In [171]:
x=torch.rand(2,3,4)
print(x)
print(x.view(2,12))
print(x.view(2,-1))

tensor([[[0.8313, 0.8116, 0.8553, 0.8163],
         [0.6291, 0.1581, 0.0801, 0.2709],
         [0.4418, 0.1935, 0.6829, 0.6547]],

        [[0.3868, 0.6922, 0.6616, 0.8053],
         [0.8367, 0.3307, 0.9885, 0.4422],
         [0.4828, 0.0281, 0.1782, 0.2079]]])
tensor([[0.8313, 0.8116, 0.8553, 0.8163, 0.6291, 0.1581, 0.0801, 0.2709, 0.4418,
         0.1935, 0.6829, 0.6547],
        [0.3868, 0.6922, 0.6616, 0.8053, 0.8367, 0.3307, 0.9885, 0.4422, 0.4828,
         0.0281, 0.1782, 0.2079]])
tensor([[0.8313, 0.8116, 0.8553, 0.8163, 0.6291, 0.1581, 0.0801, 0.2709, 0.4418,
         0.1935, 0.6829, 0.6547],
        [0.3868, 0.6922, 0.6616, 0.8053, 0.8367, 0.3307, 0.9885, 0.4422, 0.4828,
         0.0281, 0.1782, 0.2079]])


In [172]:
x=torch.tensor([1.,2.,3.],requires_grad=True)
y=torch.tensor([4.,5.,6.],requires_grad=True)
z=x+y
print(z)
print(z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [173]:
s=z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [174]:
s.backward()
print(x.grad)
print(y.grad)

tensor([1., 1., 1.])
tensor([1., 1., 1.])


In [175]:
x=torch.randn(2,2)
y=torch.randn(2,2)
print(x.requires_grad,y.requires_grad)
z=x+y
print(z.grad_fn)

x=x.requires_grad_()
y=y.requires_grad_()
z=x+y
print(z.grad_fn)
print(z.requires_grad)

new_z=z.detach()
print(new_z.grad_fn)

False False
None
True
None


In [176]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)


True
True
False


In [177]:
print(x)

tensor([[-0.3738,  1.4904],
        [-1.2968, -0.3243]], requires_grad=True)


In [178]:
print(y)

tensor([[ 0.3105, -0.3423],
        [ 0.6976,  1.4117]], requires_grad=True)


In [179]:
z=x**2+y**2
print(z)


tensor([[0.2362, 2.3385],
        [2.1684, 2.0981]], grad_fn=<AddBackward0>)


In [180]:
s=z.sum()
print(s)


tensor(6.8410, grad_fn=<SumBackward0>)


In [181]:
s.backward()
print(x.grad)
print(y.grad)

tensor([[-0.7476,  2.9808],
        [-2.5936, -0.6486]])
tensor([[ 0.6211, -0.6846],
        [ 1.3951,  2.8234]])
